// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_another_pokemon_assignment/test/favorite_pokemon_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_another_pokemon_assignment/models/local_pokemon.dart'
    as _i4;
import 'package:flutter_another_pokemon_assignment/services/local_pokemon_service_spec.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalPokemonServiceSpec].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalPokemonServiceSpec extends _i1.Mock
    implements _i2.LocalPokemonServiceSpec {
  MockLocalPokemonServiceSpec() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insertOrUpdate(_i4.LocalPokemon? pokemon) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrUpdate, [pokemon]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.LocalPokemon?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.LocalPokemon?>.value(),
          )
          as _i3.Future<_i4.LocalPokemon?>);

  @override
  _i3.Future<List<_i4.LocalPokemon>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.LocalPokemon>>.value(
              <_i4.LocalPokemon>[],
            ),
          )
          as _i3.Future<List<_i4.LocalPokemon>>);

  @override
  _i3.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
