name: 'Setup Flutter Environment'
description: 'Setup Flutter environment for CI/CD'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      working-directory: ./flutter_another_pokemon_assignment
      run: flutter pub get
      shell: bash
